version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 1000
      runas: root

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 1000
      runas: root

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 2000
      runas: root

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 1000
      runas: root

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 1000
      runas: root
